# Generated by Django 6.0.1 on 2026-01-28 04:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('tags', models.CharField(blank=True, help_text='Перечислите через запятую: например, пейзаж, море, лето', max_length=500, verbose_name='Теги')),
                ('status', models.CharField(choices=[('available', 'Доступна'), ('sold', 'Продана'), ('private', 'В частной коллекции')], default='available', max_length=20, verbose_name='Статус')),
                ('price', models.DecimalField(blank=True, decimal_places=0, help_text="Оставьте пустым для 'Цена по запросу'", max_digits=10, null=True, verbose_name='Цена (руб)')),
                ('purchase_url', models.URLField(blank=True, help_text='Ссылка на внешний магазин или форма запроса', verbose_name='Ссылка для покупки')),
                ('width_cm', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Ширина (см)')),
                ('height_cm', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Высота (см)')),
                ('created_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Год создания')),
                ('short_description', models.TextField(help_text='Для превью в каталоге', max_length=300, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Картина',
                'verbose_name_plural': 'Картины',
                'ordering': ['-created_year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название коллекции')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='collections/', verbose_name='Обложка коллекции')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тематики')),
            ],
            options={
                'verbose_name': 'Тематика',
                'verbose_name_plural': 'Тематики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artworks/%Y/%m/%d/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='artworks.artwork')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.collection', verbose_name='Коллекция'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.theme', verbose_name='Тематика'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['category'], name='artworks_ar_categor_bdf59c_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['theme'], name='artworks_ar_theme_i_7fd45d_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['collection'], name='artworks_ar_collect_381b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['created_year'], name='artworks_ar_created_7f222a_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['price'], name='artworks_ar_price_a79096_idx'),
        ),
    ]
