# Generated by Django 6.0.1 on 2026-01-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('available', 'В наличии'), ('sold', 'Нет в наличии')], default='available', max_length=20, verbose_name='Статус'),
        ),
    ]
