# Generated by Django 6.0.1 on 2026-01-30 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_alter_artwork_slug_alter_artwork_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='created_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2200)], verbose_name='Год создания'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='price',
            field=models.PositiveIntegerField(blank=True, help_text="Оставьте пустым для 'Цена по запросу'", null=True, verbose_name='Цена (руб)'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='purchase_url',
            field=models.URLField(blank=True, help_text='Ссылка на внешний магазин или форма запроса, по умалчанию ссылка на контакты', verbose_name='Ссылка для покупки'),
        ),
    ]
