# Generated by Django 6.0.1 on 2026-01-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_alter_artwork_created_year_alter_artwork_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='URL поста'),
        ),
    ]
