# Generated by Django 6.0.1 on 2026-04-01 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время просмотра')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_log', to='artworks.artwork', verbose_name='Картина')),
            ],
            options={
                'verbose_name': 'Просмотр',
                'verbose_name_plural': 'Просмотры',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['viewed_at'], name='analytics_a_viewed__1ef4f4_idx')],
            },
        ),
    ]
