# Generated by Django 6.0.1 on 2026-04-01 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('blog', '0002_remove_blogpost_blog_blogpo_status_9c1956_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время просмотра')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_log', to='blog.blogpost', verbose_name='Пост блога')),
            ],
            options={
                'verbose_name': 'Просмотр поста',
                'verbose_name_plural': 'Просмотры постов',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['viewed_at'], name='analytics_b_viewed__cbdd8c_idx')],
            },
        ),
    ]
