# Generated by Django 6.0.1 on 2026-01-29 04:00

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL поста')),
                ('tags', models.CharField(blank=True, help_text='Перечислите теги через запятую', max_length=500, verbose_name='Теги')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержимое')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('preview_image', models.ImageField(blank=True, help_text='Изображение для превью в списке постов', null=True, upload_to='blog/previews/%Y/%m/%d/', verbose_name='Превью изображение')),
                ('excerpt', models.TextField(blank=True, help_text='Если оставить пустым, будет сгенерировано автоматически', max_length=500, verbose_name='Краткое описание')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Пост блога',
                'verbose_name_plural': 'Посты блога',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='blog_blogpo_status_9c1956_idx'), models.Index(fields=['author'], name='blog_blogpo_author__0d5a17_idx'), models.Index(fields=['created_at'], name='blog_blogpo_created_ddb27d_idx')],
            },
        ),
    ]
