# Generated by Django 6.0.1 on 2026-01-30 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blogpost',
            name='blog_blogpo_status_9c1956_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogpost',
            name='blog_blogpo_created_ddb27d_idx',
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', '-published_at'], name='blog_blogpo_status_c0e87f_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', '-views'], name='blog_blogpo_status_42090b_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', '-created_at'], name='blog_blogpo_status_8774cb_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='blog_blogpo_slug_361555_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['tags'], name='blog_blogpo_tags_66add3_idx'),
        ),
    ]
